runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: application.app
- url: /(.*)/(.*)
  script: walk.application
  
libraries:
  - name: ssl
    version: latest